#!/usr/bin/env python

#------------------------------------------------------------------------
#datacombine.py, a code written by Karbo in the summer of 2017.
#This code reads the data out of the individual datafiles generated by
#multiple makedata.sh runs and combines them into one file. This is mainly
#for use when running a job array.
#The code takes two arguments, the name of the data files and number to read.
#------------------------------------------------------------------------

import sys
import linecache

def main():
    name = sys.argv[1] #name of datafiles to read
    num = int(sys.argv[2]) #which files to read

    outfile = open('./'+str(name)+'.dat', 'w')

    for i in range(num):
        infile = open('./'+str(name)+str(i+1)+'.dat', 'r')
        content = infile.read()
        infile.close()

        outfile.write(content)

        
main()
